replay-test: kotlin: add binders for Kotlin data and value classes
The "@Global" binding annotation works nicely with data class,
so no extra "@As" annotation needed in the controller classes.

In the other hand, the usages of value class needs to be annotated
by "@As(binder = ...)" in the controller classes.
Annotating the whole value class with "@As(binder = ...)" doesn't help.
Annotating the whole value class with "@Global" causes the following:

java.lang.ClassCastException: class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to class java.lang.Class (sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl and java.lang.Class are in module java.base of loader 'bootstrap')

While at it rename the printForced(Long) to printDirect(Long)
and introduce printForced(User).